include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    constant_identifier_names: ignore
    unused_import: ignore
    unnecessary_string_interpolations: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    deprecated_member_use: ignore
    unnecessary_brace_in_string_interps: ignore
    unnecessary_null_aware_expression: ignore
    unnecessary_null_comparison: ignore
    unused_local_variable: ignore
    unnecessary_cast: ignore
    use_build_context_synchronously: ignore
    prefer_final_fields: ignore

linter:
  rules:
    constant_identifier_names: false
    unnecessary_string_interpolations: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    unused_import: false
    deprecated_member_use: false
