import 'dart:convert';
import 'dart:io';

Map<String, String> flatten(Map map, [String prefix = '']) {
  final out = <String, String>{};
  map.forEach((k, v) {
    final key = prefix.isEmpty ? k : prefix + '_' + k;
    if (v is String) {
      out[key] = v;
    } else if (v is Map) {
      out.addAll(flatten(Map<String, dynamic>.from(v), key));
    } else {
      out[key] = v.toString();
    }
  });
  return out;
}

String dartEscape(String s) => s.replaceAll('\\', r'\\').replaceAll("'", "\\'");

void main() async {
  final root = Directory.current.path;
  final enFile = File('\$root\\i18n\\en_US.json');
  final faFile = File('\$root\\i18n\\fa_IR.json');

  // Use platform-independent path join to be safe
  final enPath = '${root}${Platform.pathSeparator}i18n${Platform.pathSeparator}en_US.json';
  final faPath = '${root}${Platform.pathSeparator}i18n${Platform.pathSeparator}fa_IR.json';
  final en = File(enPath);
  final fa = File(faPath);

  if (!en.existsSync() || !fa.existsSync()) {
    print('i18n files not found in: ${root}${Platform.pathSeparator}i18n');
    exit(1);
  }

  final enJson = json.decode(await en.readAsString()) as Map<String, dynamic>;
  final faJson = json.decode(await fa.readAsString()) as Map<String, dynamic>;

  final enFlat = flatten(enJson);
  final faFlat = flatten(faJson);

  final allKeys = <String>{}..addAll(enFlat.keys)..addAll(faFlat.keys);
  final sortedKeys = allKeys.toList()..sort();

  final buf = StringBuffer();
  buf.writeln('// GENERATED by tool/generate_locales.dart');
  buf.writeln('// DO NOT EDIT MANUALLY - this file is generated from i18n JSON files');
  buf.writeln();
  buf.writeln('class AppTranslation {');
  buf.writeln('  static Map<String, Map<String, String>> translations = {');
  buf.writeln("    'en_US': Locales.en_US,");
  buf.writeln("    'fa_IR': Locales.fa_IR,");
  buf.writeln('  };');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('class LocaleKeys {');
  buf.writeln('  LocaleKeys._();');
  for (final k in sortedKeys) {
    final constName = k.replaceAll('.', '_');
    buf.writeln("  static const $constName = '$k';");
  }
  buf.writeln('}');
  buf.writeln();
  buf.writeln('class Locales {');

  buf.writeln('  static const en_US = {');
  for (final k in sortedKeys) {
    final v = enFlat[k] ?? '';
    buf.writeln("    '${k}': '${dartEscape(v)}',");
  }
  buf.writeln('  };');
  buf.writeln();

  buf.writeln('  static const fa_IR = {');
  for (final k in sortedKeys) {
    final v = faFlat[k] ?? '';
    buf.writeln("    '${k}': '${dartEscape(v)}',");
  }
  buf.writeln('  };');

  buf.writeln('}');

  final outFile = File('${root}${Platform.pathSeparator}lib${Platform.pathSeparator}generated${Platform.pathSeparator}locales.g.dart');
  outFile.createSync(recursive: true);
  outFile.writeAsStringSync(buf.toString());
  print('Generated ${outFile.path} with ${sortedKeys.length} keys');
}
